name: Detox

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  lint:
    uses: ./.github/workflows/lint.yml
  detox-ios-tests:
    runs-on: macos-14
    needs: lint
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm ci

      - name: Unzip assets
        run: npm run unzip:ios

      - uses: futureware-tech/simulator-action@v4
        with:
          model: "iPhone 16"
          wait_for_boot: true
          shutdown_after_job: true

      - name: Install applesimutils
        run: |
          brew tap wix/brew
          brew install applesimutils

      - name: Run Detox iOS Tests
        run: npm run test:ios
        continue-on-error: true

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: detox-ios-report
          path: detox-ios-report.json

  detox-android-tests:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Enable KVM
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: Install dependencies
        run: npm ci

      - name: Unzip assets
        run: npm run unzip:android

      - uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 36
          target: google_apis
          arch: x86_64
          profile: Nexus 6
          disable-animations: true
          avd-name: Medium_Phone_API_36
          force-avd-creation: false
          script: echo "Emulator started"
      - name: Run Detox Android Tests
        run: npm run test:android
        continue-on-error: true

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: detox-android-report
          path: detox-android-report.json

  format-detox-summary:
    needs: [detox-ios-tests, detox-android-tests]
    runs-on: ubuntu-latest
    steps:
      - name: Download iOS Report
        uses: actions/download-artifact@v4
        with:
          name: detox-ios-report
          path: ./test-results/ios

      - name: Download Android Report
        uses: actions/download-artifact@v4
        with:
          name: detox-android-report
          path: ./test-results/android

      - name: Run Detox Report Formatter
        run: npx ts-node scripts/format-detox-summary.ts
